-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 08/06/2025 às 15:10
-- Versão do servidor: 10.4.32-MariaDB
-- Versão do PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `gnews`
--
CREATE DATABASE IF NOT EXISTS `gnews` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `gnews`;

DELIMITER $$
--
-- Procedimentos
--
CREATE DEFINER=`root`@`localhost` PROCEDURE `inserir_feedback` (IN `p_noticias_id` INT, IN `p_nota_feedback` INT, IN `p_ip_user` VARCHAR(45), IN `p_comentario` TEXT)   BEGIN
    INSERT INTO FEEDBACKS (
      NOTICIAS_ID,
      NOTA_FEEDBACK,
      COMENTARIO,
      IP_USER
    )
    VALUES (
      p_noticias_id,
      p_nota_feedback,
      p_comentario,
      p_ip_user
    );
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `select_id` (IN `p_url` TEXT)   BEGIN
	SELECT id FROM noticias WHERE url = p_url;
END$$

CREATE DEFINER=`root`@`localhost` PROCEDURE `upsert_noticia` (IN `p_title` VARCHAR(255), IN `p_description` LONGTEXT, IN `p_content` LONGTEXT, IN `p_url` VARCHAR(255), IN `p_image_url` VARCHAR(255), IN `p_published_at` DATETIME, IN `p_source_name` VARCHAR(100), IN `p_source_url` VARCHAR(255))   BEGIN
  INSERT INTO NOTICIAS (
    title,
    description,
    content,
    url,
    image_url,
    published_at,
    source_name,
    source_url
  ) VALUES (
    p_title,
    p_description,
    p_content,
    p_url,
    p_image_url,
    p_published_at,
    p_source_name,
    p_source_url
  )
  ON DUPLICATE KEY UPDATE
    title        = VALUES(title),
    description  = VALUES(description),
    content      = VALUES(content),
    image_url    = VALUES(image_url),
    published_at = VALUES(published_at),
    source_name  = VALUES(source_name),
    source_url   = VALUES(source_url),
    fetched_at   = CURRENT_TIMESTAMP;
END$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Estrutura para tabela `feedbacks`
--

CREATE TABLE `feedbacks` (
  `FEEDBACKS_ID` int(11) NOT NULL,
  `NOTICIAS_ID` int(11) NOT NULL,
  `NOTA_FEEDBACK` decimal(1,0) NOT NULL,
  `DATA_FEEDBACK` timestamp NOT NULL DEFAULT current_timestamp(),
  `COMENTARIO` text DEFAULT NULL,
  `IP_USER` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Acionadores `feedbacks`
--
DELIMITER $$
CREATE TRIGGER `calcular_media` AFTER INSERT ON `feedbacks` FOR EACH ROW BEGIN
    DECLARE NOVA_MEDIA DECIMAL(3,1);

    -- Calcula a nova média da noticia
    SELECT AVG(NOTA_FEEDBACK) INTO NOVA_MEDIA 
    FROM FEEDBACKS 
    WHERE NOTICIAS_ID = NEW.NOTICIAS_ID;

    -- Atualiza a nova média da noticia
    UPDATE NOTICIAS
    SET MEDIA_NOTICIA = NOVA_MEDIA
    WHERE id = NEW.NOTICIAS_ID;
END
$$
DELIMITER ;

-- --------------------------------------------------------

--
-- Estrutura para tabela `noticias`
--

CREATE TABLE `noticias` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `content` text DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `published_at` datetime DEFAULT NULL,
  `source_name` varchar(100) DEFAULT NULL,
  `source_url` varchar(255) DEFAULT NULL,
  `fetched_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `lang` varchar(10) DEFAULT 'pt',
  `MEDIA_NOTICIA` decimal(3,1) DEFAULT 0.0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Despejando dados para a tabela `noticias`
--

INSERT INTO `noticias` (`id`, `title`, `description`, `content`, `url`, `image_url`, `published_at`, `source_name`, `source_url`, `fetched_at`, `lang`, `MEDIA_NOTICIA`) VALUES
(64, 'Gripe Aviária: Secretaria de Saúde monitora oito pessoas no DF', 'A doença, causada pelo vírus H5N1, é transmitida pelo contato direto com animais contaminados', 'Caso de gripe aviária foi confirmado no Zoológico de Brasília. No DF, oito pessoas são monitoradas - (crédito: Ed Alves CB/DA Press)\nA Secretaria de Saúde monitora oito pessoas que tiveram contato com ave silvestre morta no Distrito Federal. Após det... [902 chars]', 'https://www.correiobraziliense.com.br/cidades-df/2025/06/7164685-gripe-aviaria-secretaria-de-saude-monitora-oito-pessoas-no-df.html', 'https://midias.correiobraziliense.com.br/_midias/jpg/2025/05/29/675x450/1_29052025ea_31-52978469.jpg?20250604122007?20250604122007', '2025-06-04 15:21:00', 'Correio Braziliense', 'https://www.correiobraziliense.com.br', '2025-06-04 17:38:42', 'pt', 5.0),
(65, 'Morten Harket, vocalista da banda a-ha, é diagnosticado com Parkinson', 'Morten Harket, 65, vocalista da banda norueguesa a-ha, revelou que foi diagnosticado com a doença de Parkinson', 'Morten Harket, 65, vocalista da banda norueguesa a-ha, revelou que foi diagnosticado com a doença de Parkinson.\nO que aconteceu\nHarket destacou que recebeu o diagnóstico com serenidade. \"Não tenho problema em aceitar o diagnóstico. Com o tempo, levei... [567 chars]', 'https://www.uol.com.br/splash/noticias/2025/06/04/morten-harket-vocalista-da-banda-a-ha-revela-diagnostico-de-parkinson.htm', 'https://conteudo.imguol.com.br/c/entretenimento/8f/2017/06/09/o-cantor-do-a-ha-morten-harket-no-auge-da-banda-no-final-dos-anos-80-1497015786662_v2_615x300.jpg', '2025-06-04 15:12:05', 'UOL', 'https://www.uol.com.br', '2025-06-04 17:38:42', 'pt', 0.0),
(66, 'débito automático era só para grandes empresas; novo Pix muda jogo', 'Encontre orientações e notícias sobre economia: investimentos, finanças, negócios, carreira, cotações de Bolsas, moedas, índices econômicos e mais...', 'Então é importante destacar que ao desenvolver o Pix Automático, o Banco Central preservou integralmente seu compromisso com a segurança, transparência e a proteção do cidadão. As autorizações para pagamentos recorrentes serão sempre claras, seguras ... [1402 chars]', 'https://economia.uol.com.br/noticias/redacao/2025/06/04/debito-automatico-era-so-para-grandes-empresas-novo-pix-muda-jogo-diz-bc.htm', 'https://conteudo.imguol.com.br/c/parceiros/a5/2025/05/16/pix-supera-transacoes-com-cartao-boleto-e-cheque-no-brasil-somadas-1747417187853_v2_615x300.jpg', '2025-06-04 14:37:01', 'UOL Economia', 'https://economia.uol.com.br', '2025-06-04 17:16:07', 'pt', 0.0),
(69, 'Empresa japonesa faz segunda tentativa de pouso na Lua', 'A empresa japonesa de exploração espacial ispace colocou em ação o seu segundo plano de tentativa de pouso na Lua - o primeiro, operado em 2023, fracassou.', 'A empresa japonesa de exploração espacial ispace colocou em ação o seu segundo plano de tentativa de pouso na Lua - o primeiro, operado em 2023, fracassou. De acordo com a companhia, a sonda Resilience tem previsão de pouso no satélite natural nesta ... [558 chars]', 'https://www.uol.com.br/tilt/ultimas-noticias/estado/2025/06/04/empresa-japonesa-faz-segunda-tentativa-de-pouso-na-lua.htm', 'https://conteudo.imguol.com.br/4a/2023/04/26/takeshi-hakamada-fundador-da-ispace-durante-transmissao-da-tentativa-de-pouso-da-sonda-na-lua-1682499252794_v2_615x300.jpg', '2025-06-04 15:08:11', 'UOL', 'https://www.uol.com.br', '2025-06-04 17:38:42', 'pt', 0.0),
(71, 'Fluminense receberá incentivo do Governo através de empresa do ex-jogador Ibson; entenda', 'O Fluminense irá receber um incentivo do Governo do Rio de Janeiro durante o Mundial; o curioso é como o dinheiro chegará ao Clube', 'O Governo vai patrocinar os times cariocas no torneio\nIncentivo do Governo\nO Fluminense, a exemplo do rivais Flamengo e Botafogo, vai receber um incentivo do Governo do Rio de Janeiro durante a participação no Mundial de Clubes da FIFA. O torneio ser... [1406 chars]', 'https://www.netflu.com.br/fluminense-recebera-incentivo-do-governo-atraves-de-outra-empresa-entenda/', 'https://www.netflu.com.br/wp-content/uploads/2025/06/WhatsApp-Image-2025-06-04-at-10.41.03.jpeg', '2025-06-04 14:20:44', 'netflu.com.br', 'https://www.netflu.com.br', '2025-06-04 17:16:07', 'pt', 0.0),
(72, 'Segredo inédito em Vale Tudo: Odete esconde filho que foi dado como morto', 'Qual o segredo de Odete Roitman (Debora Bloch) e Nice (Teca Pereira) em Vale Tudo. Filho dado como morto está vivo e em uma cadeira de rodas', 'Um novo segredo começou a ser descortinado no capítulo desta terça (3) de Vale Tudo. Odete Roitman (Debora Bloch) visitou Nice (Teca Pereira), que exigiu o dobro do dinheiro que recebe para ela \"fazer o que tem que fazer\". A cena viralizou nas redes ... [3254 chars]', 'https://noticiasdatv.uol.com.br/noticia/novelas/segredo-inedito-em-vale-tudo-odete-esconde-filho-que-foi-dado-como-morto-137309', 'https://noticiasdatv.uol.com.br/media/uploads/artigos_2024/globo-vale-tudo-odete-segredo-debora-bloch.jpeg', '2025-06-04 14:13:00', 'Notícias da TV', 'https://noticiasdatv.uol.com.br', '2025-06-04 17:16:07', 'pt', 0.0),
(73, 'acompanhe em tempo real a Bolsa de Valores', 'Acompanhe o que movimenta a bolsa, ações, dólar, juros e commodities nos negócios do pregão desta quarta-feira (04).', 'update 10h24\nO real permanecerá praticamente estável nos próximos meses, contido por uma deterioração nas contas externas do país, mostrou uma pesquisa da Reuters. O real está se aproximando do meio do ano em melhor forma do que o esperado no início ... [1112 chars]', 'https://www.infomoney.com.br/mercados/ibovespa-hoje-bolsa-de-valores-ao-vivo-04062025/', 'https://www.infomoney.com.br/wp-content/uploads/2025/05/Ibovespa-1-10.png?quality=70', '2025-06-04 14:07:24', 'InfoMoney', 'https://www.infomoney.com.br', '2025-06-04 17:16:07', 'pt', 0.0),
(74, 'Moraes determina prisão preventiva de Carla Zambelli após saída do país: \'Objetivo de se furtar à aplicação da lei\'', 'Deputada federal anunciou que deixou o Brasil depois de ser condenada à prisão; PGR pediu a prisão preventiva ao STF', 'O ministro Alexandre de Moraes, do Supremo Tribunal Federal (STF), decretou a prisão preventiva da deputada federal Carla Zambelli (PL-SP). Ela foi condenada pela Corte a 10 anos de prisão e anunciou na terça-feira que deixou o Brasil.\n\"No caso de CA... [2080 chars]', 'https://oglobo.globo.com/politica/noticia/2025/06/04/moraes-determina-prisao-preventiva-de-carla-zambelli.ghtml', 'https://s2-oglobo.glbimg.com/aqh450svGUMlL23vmULBPMcOm0s=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2025/f/N/aLt4tLQc6DUAgcALvBSg/whatsapp-image-2025-05-15-at-15.04.38.jpeg', '2025-06-04 14:03:15', 'O Globo', 'https://oglobo.globo.com', '2025-06-04 17:16:07', 'pt', 0.0),
(75, 'Alemanha x Portugal Palpites', 'Alemanha x Portugal duelam nesta quarta (04/06) pela semifinal da Liga das Nações hoje! Confira nosso palpite, dicas de apostas, onde assistir, horário e as prováveis escalações!', 'Alemanha x Portugal se enfrentam em partida válida pela semifinal da Nations League 2024/25. O duelo acontecerá nesta quarta (04), às 16:00 (horário de Brasília), em Munique, na Allianz Arena. Ambas as equipes chegam invictas na competição e com camp... [5668 chars]', 'https://www.gazetaesportiva.com/apostas/prognosticos/futebol/alemanha-x-portugal-04-06-2025', 'https://apostas.gazetaesportiva.com/static/wp/Alemanha-x-Portugal.webp', '2025-06-04 14:02:12', 'Gazeta Esportiva', 'https://www.gazetaesportiva.com', '2025-06-04 17:16:07', 'pt', 0.0),
(76, 'Sesab não responde sobre dados de pesquisa e acusa Correio de divulgar \'fake news\'', 'CORREIO recebeu com surpresa reação da Sesab à publicação da reportagem, que foi procurada para responder sobre pesquisa feita pela Confederação Nacional dos Municípios (CNM)', 'COMO ASSIM?\nSesab não responde sobre dados de pesquisa e acusa Correio de divulgar \'fake news\'\nCORREIO recebeu com surpresa reação da Sesab à publicação da reportagem, que foi procurada para responder sobre pesquisa feita pela Confederação Nacional d... [3375 chars]', 'https://www.correio24horas.com.br/saude/sesab-nao-responde-sobre-dados-de-pesquisa-e-acusa-correio-de-divulgar-fake-news-0625', 'https://midias.correio24horas.com.br/2025/06/04/sesab-nao-responde-sobre-dados-de-pesquisa-e-acusa-correio-de-divulgar-fake-news-2753193.jpeg', '2025-06-04 13:46:38', 'Jornal Correio', 'https://www.correio24horas.com.br', '2025-06-04 17:16:07', 'pt', 0.0),
(99, 'O que faz um relacionamento durar? Veja 6 dicas de especialistas', 'VivaBem, o novo canal de saúde e bem-estar do UOL com informações confiáveis e embasadas cientificamente, dicas testadas e orientações de especialistas', 'Se antigamente era comum conhecer casais que estavam juntos há mais de 30 anos, os tempos definitivamente mudaram. Segundo dados do IBGE, o tempo médio de duração de um casamento caiu para 13,8 anos.\nEssa mudança pode ser um reflexo de muitos fatores... [584 chars]', 'https://www.uol.com.br/vivabem/noticias/redacao/2025/06/04/o-que-faz-um-relacionamento-durar-veja-6-dicas-de-especialistas.htm', 'https://conteudo.imguol.com.br/c/entretenimento/71/2022/08/19/casal-apaixonado-amor-signos-opostos-se-atraem-1660933265210_v2_615x300.jpg', '2025-06-04 16:06:56', 'UOL', 'https://www.uol.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(100, 'Por que temos tanto medo de fracassar? Motivo pode estar na infância', 'VivaBem, o novo canal de saúde e bem-estar do UOL com informações confiáveis e embasadas cientificamente, dicas testadas e orientações de especialistas', 'Essa bagagem emocional cobra seu preço. A pessoa cresce com a sensação de que nunca é boa o suficiente, não importa o quanto se esforce. Quando algo dá certo, o mérito é sempre do acaso, da sorte ou do networking. Quando dá errado? A culpa é um carim... [1034 chars]', 'https://www.uol.com.br/vivabem/noticias/redacao/2025/06/04/por-que-temos-tanto-medo-de-fracassar-motivo-pode-estar-na-infancia.htm', 'https://conteudo.imguol.com.br/c/noticias/fb/2021/08/05/sindrome-do-impostor-1628197273422_v2_615x300.jpg', '2025-06-04 15:57:32', 'UOL', 'https://www.uol.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(101, 'Clareamento dental caseiro vira febre no TikTok e Instagram; especialista alerta para os riscos', 'O que parece ser uma solução simples e barata pode trazer sérias consequências para a saúde bucal', 'O que parece ser uma solução simples e barata pode trazer sérias consequências para a saúde bucal\nNos últimos meses, vídeos de clareamento dental caseiro se tornaram virais nas redes sociais, especialmente no TikTok e no Instagram. Criadores de conte... [3008 chars]', 'https://liberal.com.br/mais/bem-estar/clareamento-dental-caseiro-vira-febre-no-tiktok-e-instagram-especialista-alerta-para-os-riscos-2402552/', 'https://liberal.com.br/wp-content/uploads/2025/06/beauty-women-fashion-concept-close-up-portrait-silly-adorable-young-blond-woman-red-turtleneck.jpg', '2025-06-04 15:00:55', 'O Liberal', 'https://liberal.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(102, 'Reforma tributária pode mudar benefícios para executivos', 'Outros itens, como planos de saúde, incentivos educacionais e vales, devem estar previstos em convenção coletiva', 'São Paulo\nA reforma tributária pode levar as empresas a reverem os benefícios dados a colaboradores e administradores, em especial o fornecimento de veículos e a cessão de imóvel para moradia.\nPela regra geral, os tributos que incidem sobre os bens e... [4945 chars]', 'https://www1.folha.uol.com.br/mercado/2025/06/reforma-tributaria-pode-levar-empresa-a-rever-veiculo-e-imovel-para-executivo.shtml', 'https://f.i.uol.com.br/fotografia/2025/04/28/1745864080680fc5908977f_1745864080_3x2_rt.jpg', '2025-06-04 15:00:00', 'Folha de S.Paulo', 'https://www1.folha.uol.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(103, 'Câmara aprova PL que obriga divulgação de lista de espera na rede pública de saúde em Pouso Alegre', 'A Câmara Municipal aprovou por unanimidade nesta terça-feira (03) um projeto que obriga a divulgação da lista de pacientes que aguardam consultas médicas em…', 'Foto: PousoAlegre • net\nA Câmara Municipal aprovou por unanimidade nesta terça-feira (03) um projeto que obriga a divulgação da lista de pacientes que aguardam consultas médicas em Pouso Alegre.\nO Projeto de Lei nº 7.979/2025, de autoria dos vereador... [1003 chars]', 'https://pousoalegre.net/139582/camara-aprova-pl-que-obriga-divulgacao-de-lista-de-espera-na-rede-publica-de-saude-em-pouso-alegre/', 'https://uploads.pousoalegre.net/2025/06/b66ec89b-7aa7-423f-86b3-cf9b1490da1b.webp', '2025-06-04 14:13:31', 'PousoAlegre.net', 'https://pousoalegre.net', '2025-06-04 17:15:32', 'pt', 0.0),
(104, 'Pix Automático: tire dúvidas, veja o que muda e como vai funcionar', 'No ar a partir do dia 16, o Pix Automático facilitará o pagamento de contas recorrentes, como planos de saúde, contas de consumo e streaming', 'O Banco Central (BC) anunciou nesta quarta-feira (4/6), em um evento em São Paulo que contou com a presença do presidente da autoridade monetária, Gabriel Galípolo, a nova modalidade do Pix – o Pix Automático.\nDe acordo com o BC, o Pix Automático fac... [5112 chars]', 'https://www.metropoles.com/negocios/pix-automatico-tire-duvidas-veja-o-que-muda-e-como-vai-funcionar', 'https://uploads.metroimg.com/wp-content/uploads/2025/02/28101929/pix-13.jpg', '2025-06-04 14:07:00', 'Metrópoles', 'https://www.metropoles.com', '2025-06-04 17:15:32', 'pt', 0.0),
(105, 'Saiba qual é o iogurte mais proteico para incorporar na dieta', 'O iogurte é rico em proteínas, cálcio, probióticos, entre outros nutrientes importantes para a saúde intestinal, óssea e imunológica', 'Conforme a nutricionista Vanessa Furstenberger relevou à coluna Claudia Meireles, o iogurte é um alimento prático e rico em proteínas, cálcio, probióticos, entre outros nutrientes importantes para a saúde intestinal, óssea e imunológica.\nSegundo ela,... [1414 chars]', 'https://www.metropoles.com/colunas/claudia-meireles/saiba-qual-e-o-iogurte-mais-proteico-para-incorporar-na-dieta', 'https://uploads.metroimg.com/wp-content/uploads/2025/06/03164222/GettyImages-1784026580.jpg', '2025-06-04 13:01:00', 'Metrópoles', 'https://www.metropoles.com', '2025-06-04 17:15:32', 'pt', 0.0),
(106, 'MG: idosa é resgatada em área de mata depois de passar a noite perdida', 'Mulher saiu de casa às 17h e não foi encontrada até a manhã seguinte. Ela foi resgatada e ficou sob observação em unidade de saúde', 'O Corpo de bombeiros resgatou ma idosa, de 65 anos, que estava perdida em uma área de mata na zona rural de Riacho dos Machados (MG), na região Norte, já por uma noite inteira. Ela foi encontrada com sinais de desidratação e levada para atendimento m... [825 chars]', 'https://www.em.com.br/gerais/2025/06/7164379-mg-idosa-e-resgatada-em-area-de-mata-depois-de-passar-a-noite-perdida.html', 'https://midias.em.com.br/_midias/jpg/2025/06/04/1000x1000/1_whatsapp_image_2025_06_04_at_05_00_02-53347846.jpeg?20250604080632?20250604080632', '2025-06-04 12:22:04', 'Estado de Minas', 'https://www.em.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(107, 'Ex-chefe da F1 fala sobre estado de saúde de Schumacher: \"Prefiro lembrar dele sorrindo\"', 'Flavio Briatore compartilhou sua perspectiva sobre o alemão, revelando a dura realidade e a preservação da memória de um sorriso', 'Peter Steffen / DPA,AFP\nFlavio Briatore, ex-dirigente da Fórmula 1 e hoje consultor executivo da Alpine, abordou a delicada recuperação do ex-piloto Michael Schumacher, mais de uma década após o grave acidente de esqui que alterou radicalmente sua ex... [1212 chars]', 'https://gauchazh.clicrbs.com.br/esportes/automobilismo/noticia/2025/06/ex-chefe-da-f1-abre-o-jogo-com-palavras-tocantes-sobre-lembrancas-de-schumacher-cmbhwa2jg003u014fbbwffgb3.html', 'https://www.rbsdirect.com.br/filestore/4/3/2/7/8/8/4_f5a1ae8b1c5aa14/4887234_db8886c82dc5fc8.jpg?w=1200&h=630&a=c&version=1575255600', '2025-06-04 12:06:06', 'Zero Hora', 'https://gauchazh.clicrbs.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(108, '12 motivos para começar a praticar corrida', 'Estudos científicos reforçam os benefícios deste tipo de atividade física para a saúde', 'Correr é uma atividade física simples e acessível, que oferece inúmeros benefícios para a saúde física e mental. Para começar, basta um bom par de tênis e roupas confortáveis. Diferentemente de outras modalidades que exigem equipamentos ou mensalidad... [5258 chars]', 'https://www.tnh1.com.br/noticia/nid/12-motivos-para-comecar-a-praticar-corrida-2668/', 'https://www.tnh1.com.br/media/_versions/feedsync/12-motivos-para-comecar-a-praticar-corrida-2668_widelg.jpg', '2025-06-04 12:05:45', 'TNH1', 'https://www.tnh1.com.br', '2025-06-04 17:15:32', 'pt', 0.0),
(159, 'Resonance: A Plague Tale Legacy vaza antes da hora', 'Resonance: A Plague Tale Legacy deve ser anunciado oficialmente amanhã no evento do Xbox.', 'Amanhã será realizado uma nova edição do que certamente contará com grandes anúncios, incluindo a revelação oficial do mais novo título da franquia A Plague Tale da Asobo Studio.\nPor meio das redes sociais, acabou vazando antes da hora a existência d... [831 chars]', 'https://www.gamevicio.com/noticias/2025/06/resonance-a-plague-tale-legacy-vazou/', 'https://www.gamevicio.com/wp-content/uploads/2025/06/tale.jpg', '2025-06-07 19:54:26', 'GameVicio', 'https://www.gamevicio.com', '2025-06-08 01:04:27', 'pt', 0.0),
(160, 'Vôlei: Brasil vence Alemanha no drama e segue 100% na Liga das Nações', 'Brasil vence Alemanha no drama e segue 100% na Liga das Nações de vôlei feminina; saiba como foi o jogo.', 'O Brasil volta à quadra amanhã, às 10h (de Brasília), para encarar a atual campeã olímpica Itália. O jogo será o último da seleção no Rio de Janeiro nesta edição da Liga das Nações.\nA equipe verde-amarela busca o título inédito. Presente nas seis pri... [737 chars]', 'https://www.uol.com.br/esporte/ultimas-noticias/2025/06/07/volei-liga-das-nacoes-alemanha-brasil.htm', 'https://conteudo.imguol.com.br/c/esporte/30/2025/06/07/jogadoras-do-brasil-celebram-ponto-contra-a-alemanha-em-duelo-pela-liga-das-nacoes-1749320092673_v2_615x300.jpg', '2025-06-07 18:51:40', 'UOL', 'https://www.uol.com.br', '2025-06-07 23:04:00', 'pt', 0.0),
(161, 'Moraes determina prisão definitiva de Carla Zambelli', 'Ministro também determinou a perda de mandato da parlamentar', 'Ministro também notifica Câmara para cassação de mandato; deputada licenciada está na Itália e foi incluída na lista vermelha da Interpol\nO ministro Alexandre de Moraes, do Supremo Tribunal Federal (STF), ordenou neste sábado (7) o cumprimento de pen... [1889 chars]', 'https://www.cnnbrasil.com.br/politica/moraes-determina-prisao-definitiva-de-carla-zambelli/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/05/54534250048_d5133219a0_o.jpg', '2025-06-07 18:15:47', 'CNN Brasil', 'https://www.cnnbrasil.com.br', '2025-06-07 22:40:55', 'pt', 0.0),
(231, 'Projeto que anula IOF pode ser pautado na semana que vem', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Motta defendeu a reforma administrativa e a modernizações nos serviços públicos. \"Modernizar para que, ao menor custo, se consiga entregar serviços de mais qualidade à nossa população. É essa, sem dúvida alguma, a principal missão dessa reforma admin... [1892 chars]', 'https://noticias.uol.com.br/politica/ultimas-noticias/2025/06/07/projeto-que-anula-iof-pode-ser-pautado-na-semana-que-vem-diz-motta.htm', 'https://conteudo.imguol.com.br/c/noticias/09/2025/06/07/presidente-da-camara-hugo-motta-participa-de-evento-no-guaruja-litoral-de-sp-1749309174425_v2_615x300.jpg', '2025-06-07 17:59:44', 'UOL Notícias', 'https://noticias.uol.com.br', '2025-06-07 22:00:55', 'pt', 0.0),
(232, 'Trump diz que Musk \"sofrerá as consequências\" se financiar Democratas', 'Presidente falou em entrevista a uma emissora americana', 'Presidente norte-americano, Donald Trump, e presidente-executivo da Tesla, Elon Musk, na Pensilvânia, EUA\nPresidente falou em entrevista a uma emissora americana\nTrump diz que Musk \"sofrerá as consequências\" se financiar Democratas\nO presidente Donal... [860 chars]', 'https://www.cnnbrasil.com.br/internacional/trump-diz-que-musk-sofrera-as-consequencias-se-financiar-democratas/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/05/2025-05-01T173234Z_1_LYNXMPEL401X4_RTROPTP_4_USA-TRUMP-GOLDEN-DOME.jpg', '2025-06-07 17:45:21', 'CNN Brasil', 'https://www.cnnbrasil.com.br', '2025-06-07 22:00:55', 'pt', 0.0),
(233, 'Sangue é encontrado em carro de empresário achado morto no Autódromo de SP', 'Adalberto Amarilio dos Santos Junior foi achado morto em um buraco nas proximidades do Autódromo de Interlagos; causa da morte ainda não foi esclarecida', 'O corpo do empresário Adalberto Amarilio dos Santos Junior foi encontrado perto do Autódromo de Interlagos, em São Paulo\nO corpo do empresário Adalberto Amarilio dos Santos Junior foi encontrado perto do Autódromo de Interlagos, em São Paulo • Reprod... [3486 chars]', 'https://www.cnnbrasil.com.br/nacional/sudeste/sp/sangue-e-encontrado-em-carro-de-empresario-achado-morto-no-autodromo-de-sp/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/06/74.jpg', '2025-06-07 17:21:12', 'CNN Brasil', 'https://www.cnnbrasil.com.br', '2025-06-07 21:20:46', 'pt', 0.0),
(234, 'Esposa revela patrimônio milionário de empresário encontrado em buraco em Interlagos', 'Apartamento, casa, carros de luxo e empresa. Juntando tudo, Adalberto Amarilio dos Santos Junior, o empresário encontrado morto em um buraco próximo ao', 'Esposa revela patrimônio milionário de empresário encontrado em buraco em Interlagos\nAdalberto também não estava sendo ameaçado, segundo familiares e amigos do empresário\nApartamento, casa, carros de luxo e empresa. Juntando tudo, Adalberto Amarilio ... [3315 chars]', 'https://www.nsctotal.com.br/noticias/esposa-revela-patrimonio-milionario-de-empresario-encontrado-em-buraco-em-interlagos', 'https://img.nsctotal.com.br/wp-content/uploads/2025/06/empresario-5.jpg', '2025-06-07 16:33:20', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-07 21:20:46', 'pt', 0.0),
(235, 'Coco Gauff é campeã em Roland Garros após vencer Sabalenka de virada', 'Este é o segundo título de Grand Slam da carreira da norte-americana', 'Este é o segundo título de Grand Slam da carreira da norte-americana\nCoco Gauff lutou para sair de um set atrás e surpreender a principal cabeça de chave Aryna Sabalenka por 2 sets a 1, parciais de 6-7(5), 6-2 e 6-4 na final de Roland Garros, neste s... [1730 chars]', 'https://www.cnnbrasil.com.br/esportes/tenis/coco-gauff-e-campea-em-roland-garros-apos-vencer-sabalenka-de-virada/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/06/coco-gauff-e1749312708575.jpeg', '2025-06-07 16:17:14', 'CNN Brasil', 'https://www.cnnbrasil.com.br', '2025-06-07 21:20:46', 'pt', 0.0),
(236, 'Sem Neymar, Santos vence a Portuguesa Santista em jogo-treino', 'Santos vence a Portuguesa Santista em jogo-treino; Neymar não participou da atividade.', 'Sem compromissos devido à data Fifa, o Santos realizou um jogo-treino na manhã de hoje, no CT Rei Pelé, e venceu a Portuguesa Santista por 2 a 1. Neymar foi desfalque por não ter participado integralmente das atividades do dia anterior.\nThaciano e Ti... [292 chars]', 'https://www.uol.com.br/esporte/futebol/ultimas-noticias/gazeta-esportiva/2025/06/07/sem-neymar-santos-vence-jogo-treino-contra-a-portuguesa-santista.htm', 'https://conteudo.imguol.com.br/c/esporte/01/2025/06/07/santos-vence-jogo-treino-contra-a-portuguesa-santista-1749313092263_v2_615x300.jpg', '2025-06-07 15:53:47', 'UOL', 'https://www.uol.com.br', '2025-06-07 21:20:46', 'pt', 0.0),
(237, 'Galípolo vê oportunidade em \'consenso\' sobre fiscal e diz que próxima decisão sobre juros está aberta', 'Presidente do BC diz que ambiente de diálogo entre os Poderes pode abrir caminho para reformas estruturais', 'O presidente do Banco Central, Gabriel Galípolo, afirmou neste sábado que há um movimento positivo de convergência entre Executivo, Legislativo e setor privado em torno de uma agenda estrutural voltada para o equilibrio fiscal. Para ele, esse ambient... [1994 chars]', 'https://oglobo.globo.com/economia/noticia/2025/06/07/galipolo-ve-oportunidade-em-consenso-sobre-agenda-fiscal-e-diz-que-proximas-decisoes-do-bc-estao-abertas.ghtml', 'https://s2-oglobo.glbimg.com/INeGQ--mlhkAQaY0q_1uIEia5Jw=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2025/y/8/l6DgsnRJCi4DwlPRE7eA/forumesferaguaruja2025-ianrassari-6572.jpg', '2025-06-07 15:34:43', 'O Globo', 'https://oglobo.globo.com', '2025-06-07 21:20:46', 'pt', 0.0),
(238, 'em noite de amor, Leila expõe primeira vez a Marco Aurélio', 'Leila (Carolina Dieckmann) e Marco Aurélio (Alexandre Nero) vão transar pela primeira vez em \'Vale Tudo\'', 'Leila fica constrangida, mas, aos poucos, abre o coração e expõe que sempre teve problemas de confiança. Após Marco Aurélio incentivá-la a ser sincera, ela revela: \"É que... Eu acabei de descobrir que prazer e orgasmo são duas coisas diferentes\".\nMar... [781 chars]', 'https://www.uol.com.br/splash/noticias/2025/06/07/noite-de-amor-leila-confessa-primeira-vez-a-marco-aurelio-em-vale-tudo.htm', 'https://conteudo.imguol.com.br/c/entretenimento/08/2025/06/07/em-vale-tudo-leila-carolina-dieckmann-faz-revelacao-a-marco-aurelio-alexandre-nero-1749327830277_v2_615x300.jpg', '2025-06-07 20:31:00', 'UOL', 'https://www.uol.com.br', '2025-06-08 01:04:27', 'pt', 0.0),
(239, 'Brasil vence a Alemanha de virada pela Liga das Nações de Vôlei (VNL) feminino 2025', 'O Brasil venceu a Alemanha por 3 sets a 2 na tarde deste sábado (7), no Maracanãzinho, no Rio de Janeiro (RJ), pelo 4º dia de jogos. Equipe comandada por', 'Brasil vence a Alemanha de virada pela Liga das Nações de Vôlei (VNL) feminino 2025\nSeleção Brasileira garante virada contra adversária e segue com 100% de aproveitamento\nO Brasil venceu a Alemanha por 3 sets a 2 na tarde deste sábado (7), no Maracan... [1604 chars]', 'https://www.nsctotal.com.br/noticias/brasil-vence-a-alemanha-de-virada-pela-liga-das-nacoes-de-volei-vnl-feminino-2025', 'https://img.nsctotal.com.br/wp-content/uploads/2025/06/Brasil-vence-a-Alemanha-na-VNL.jpg', '2025-06-07 20:08:13', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 01:04:27', 'pt', 0.0),
(241, 'Zenit pagará multa de Gerson após o Mundial; valor agrada ao Flamengo', 'Gerson está perto de trocar o Flamengo pelo Zenit, da Rússia. O clube de São Petersburgo irá arcar com a multa rescisória', 'Gerson está perto de trocar o Flamengo pelo Zenit, da Rússia. O clube de São Petersburgo irá arcar com a multa rescisória de 25 milhões de euros (aproximadamente R$ 159 milhões) para tirar o meio-campista do Rubro-Negro, que exige receber o valor à v... [1629 chars]', 'https://www.lance.com.br/flamengo/zenit-pagara-multa-de-gerson-apos-o-mundial-de-clubes-valor-agrada-o-flamengo.html', 'https://lncimg.lance.com.br/cdn-cgi/image/width=1280,height=720,quality=75,fit=cover,format=webp/uploads/2025/06/Gerson-Flamengo-scaled-aspect-ratio-512-320-1.jpg', '2025-06-07 19:46:24', 'LANCE!', 'https://www.lance.com.br', '2025-06-07 23:04:00', 'pt', 0.0),
(242, 'Ancelotti tem papo individual com Raphinha; quem sai do time?', 'Raphinha deve ser titular da seleção brasileira contra o Paraguai.', 'A dúvida é quem sairá da equipe para Raphinha entrar. A comissão técnica permitiu apenas 15 minutos para a imprensa e não deu pistas.\nPolivalente, Raphinha pode jogar como meia, ponta ou até falso 9. Estêvão, Richarlison ou um dos volantes poderiam s... [718 chars]', 'https://www.uol.com.br/esporte/futebol/ultimas-noticias/2025/06/07/de-volta-raphinha-tem-papo-individual-com-ancelotti-quem-sai-do-time.htm', 'https://conteudo.imguol.com.br/c/esporte/8f/2025/06/07/raphinha-em-treino-da-selecao-brasileira-1749325031138_v2_615x300.jpg', '2025-06-07 19:43:18', 'UOL', 'https://www.uol.com.br', '2025-06-07 23:04:00', 'pt', 0.0),
(243, 'Torcedores cricitam elenco do Corinthians após gol de Memphis pela Holanda', 'Memphis foi o autor do primeiro gol da Holanda sobre a Finlândia, neste sábado (7), pelas Eliminatórias europeias da Copa do Mundo de 2026.', 'Memphis foi o autor do primeiro gol da Holanda sobre a Finlândia, neste sábado (7), pelas Eliminatórias europeias da Copa do Mundo de 2026. O tento do atleta virou assunto entre os torcedores do Corinthians. Parte da torcida alvinegra aproveitou o mo... [1338 chars]', 'https://www.lance.com.br/fora-de-campo/torcedores-cricitam-elenco-do-corinthians-apos-gol-de-memphis-pela-holanda.html', 'https://lncimg.lance.com.br/cdn-cgi/image/width=1280,height=720,quality=75,fit=cover,format=webp/uploads/2025/06/AFP__20250607__49KT2WD__v1__HighRes__FblWc2026QualifiersFinNed-scaled-aspect-ratio-512-320.jpg', '2025-06-07 19:43:18', 'LANCE!', 'https://www.lance.com.br', '2025-06-07 23:04:00', 'pt', 0.0),
(346, 'Tarcísio define saída antecipada de Derrite do governo', 'Secretário de Segurança Pública deverá deixar o cargo até dezembro e retornar ao Congresso; titular da Administração Penitenciária é mais cotado para assumir', 'São Paulo\nCandidato declarado ao Senado, o secretário de Segurança Pública, Guilherme Derrite (PP), deverá deixar a gestão Tarcísio de Freitas (Republicanos) até o final do ano. O governador e o secretário já negociaram a saída, a princípio programad... [7268 chars]', 'https://www1.folha.uol.com.br/cotidiano/2025/06/descontente-tarcisio-define-saida-antecipada-de-derrite-do-governo.shtml', 'https://f.i.uol.com.br/fotografia/2024/11/07/1731012612672d2804562d2_1731012612_3x2_rt.jpg', '2025-06-07 20:44:00', 'Folha de S.Paulo', 'https://www1.folha.uol.com.br', '2025-06-08 01:04:27', 'pt', 0.0),
(360, 'Moraes determina prisão definitiva de Carla Zambelli e autoriza extradição da Itália', 'Na decisão, ministro do STF afirmou que a deputada se \'evadiu do distrito da culpa com o objetivo de se furtar à aplicação da lei penal\'', 'O ministro Alexandre de Moraes, do Supremo Tribunal Federal (STF), determinou neste sábado (7) a prisão definitiva da deputada Carla Zambelli (PL-SP) e autorizou o início do processo formal de extradição junto ao governo da Itália, onde ela estaria f... [1177 chars]', 'https://www.itatiaia.com.br/politica/2025/06/07/moraes-determina-prisao-definitiva-de-carla-zambelli-e-autoriza-extradicao-para-a-italia', 'https://medias.itatiaia.com.br/dims4/default/a488ec7/2147483647/strip/true/crop/1200x630+0+23/resize/1200x630!/format/webp/quality/90/?url=https%3A%2F%2Fk2-prod-radio-itatiaia.s3.us-east-1.amazonaws.com%2Fbrightspot%2F4a%2Fdd%2Fa48aeed87abbdc4d2fd3c468e76', '2025-06-07 18:29:30', 'Rádio Itatiaia', 'https://www.itatiaia.com.br', '2025-06-07 22:40:55', 'pt', 0.0),
(394, 'Irã acusa Trump de racismo por veto a estrangeiros', 'Presidente dos EUA assinou decreto com a proibição de entrada sob a justificativa de preocupação com segurança nacional', 'AFP e Reuters\nO Irã criticou neste sábado (7) a decisão do presidente dos Estados Unidos, Donald Trump de proibir a entrada de iranianos em seu país, afirmando que a medida é sinal de uma \"mentalidade supremacista e racista\".\nAlém do Irã, outros 11 p... [2592 chars]', 'https://www1.folha.uol.com.br/mundo/2025/06/ira-acusa-trump-de-racismo-e-islamofobia-por-veto-a-estrangeiros-de-12-paises.shtml', 'https://f.i.uol.com.br/fotografia/2025/06/04/17490821566840e02c947cf_1749082156_3x2_xl.jpg', '2025-06-07 21:37:00', 'Folha de S.Paulo', 'https://www1.folha.uol.com.br', '2025-06-08 01:04:27', 'pt', 0.0),
(405, 'Alexandre de Moraes determina pedido de extradição de Carla Zambelli', 'O Ministro Alexandre de Moraes determinou, neste sábado (7), que o Ministério da Justiça formalize o pedido de extradição da deputada federal Carla', 'Alexandre de Moraes determina pedido de extradição de Carla Zambelli\nMinistro ainda solicitou a comunicação imediata à Câmara dos Deputados sobre a perda do mandato de Zambelli (Foto: Antonio Augusto, STF)\nO Ministro Alexandre de Moraes determinou, n... [1582 chars]', 'https://www.nsctotal.com.br/noticias/alexandre-de-moraes-determina-pedido-que-extradicao-de-carla-zambelli', 'https://img.nsctotal.com.br/wp-content/uploads/2025/03/STF-julga-denuncia-contra-Bolsonaro-e-mais-7-acusados-por-tentativa-de-golpe-4-1-1.jpg', '2025-06-07 19:41:51', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-07 23:04:00', 'pt', 0.0),
(413, 'Veja os números sorteados no concurso 2873 da Mega-Sena, com prêmio de R$ 51 milhões', 'A Caixa Econômica Federal sorteia neste sábado (7) o concurso 2873 da Mega-Sena, com prêmio acumulado em R$ 11 milhões. O sorteio acontece a partir das', 'Veja os números sorteados no concurso 2873 da Mega-Sena, com prêmio de R$ 51 milhões\nSorteio acontece a partir das 20h no Youtube da Caixa Econômica Federal\nA Caixa Econômica Federal sorteia neste sábado (7) o concurso 2873 da Mega-Sena, com prêmio a... [1493 chars]', 'https://www.nsctotal.com.br/noticias/veja-os-numeros-sorteados-no-concurso-2873-da-mega-sena-com-premio-de-r-51-milhoes', 'https://img.nsctotal.com.br/wp-content/uploads/2025/05/mega-sena.jpg', '2025-06-07 22:54:08', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 01:52:07', 'pt', 0.0),
(414, 'Neymar Jr. é afastado após diagnóstico e Santos se pronuncia', 'O departamento médico da equipe da Baixada Santista afirmou que Neymar Júnior foi afastado das atividades para repouso', 'O jogador Neymar Júnior, do Santos, foi diagnosticado com covid-19, informou o Santos Futebol Clube neste sábado (7/6). Diante do quadro de saúde, a equipe da Baixada Santista afirmou que o atleta será afastado das atividades para tratamento. Ele dev... [2160 chars]', 'https://www.metropoles.com/colunas/fabia-oliveira/neymar-jr-e-afastado-apos-diagnostico-e-santos-se-pronuncia', 'https://uploads.metroimg.com/wp-content/uploads/2025/05/27161809/neymar-54.jpg', '2025-06-07 22:00:00', 'Metrópoles', 'https://www.metropoles.com', '2025-06-08 01:13:58', 'pt', 0.0),
(415, 'Garota do Momento: resumo da semana (9 a 14/06) tem confissão, incêndio e fim de mistério', 'Paradeiro do colar Mystique é revelado esta semana em Garota do Momento. Veja o resumo da semana divulgado pela Globo', 'Garota do Momento: resumo da semana (9 a 14/06) tem confissão, incêndio e fim de mistério\nO paradeiro do colar Mystique é revelado esta semana em Garota do Momento. Nesta semana, depois de Bia (Maisa) ver que pode perder Ronaldo, ela começa a contar ... [4857 chars]', 'https://www.nsctotal.com.br/noticias/garota-do-momento-resumo-da-semana-9-a-14-06-tem-confissao-incendio-e-fim-de-misterio', 'https://img.nsctotal.com.br/wp-content/uploads/2025/06/Destaques-da-semana-de-Garota-do-Momento-7.jpg', '2025-06-07 21:44:31', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 01:13:58', 'pt', 0.0),
(419, 'Empresários elevam pressão sobre governo Lula', 'Evento reuniu nomes de peso do PIB para defender controle dos gastos públicos', 'São Paulo\nO empresariado avançou em uma ofensiva contra o apetite arrecadatório do governo Lula neste sábado (7) durante um evento organizado pelo grupo Esfera, de João Camargo, em Guarujá.\nO alvo da reação é o aumento do IOF (Imposto sobre Operações... [3926 chars]', 'https://www1.folha.uol.com.br/mercado/2025/06/empresarios-elevam-pressao-sobre-governo-lula-com-criticas-de-wesley-batista-e-andre-esteves.shtml', 'https://f.i.uol.com.br/fotografia/2025/06/07/17493308166844ab8043f97_1749330816_3x2_rt.jpg', '2025-06-07 21:44:00', 'Folha de S.Paulo', 'https://www1.folha.uol.com.br', '2025-06-08 01:04:27', 'pt', 0.0),
(423, 'Neymar é diagnosticado com COVID-19 e é afastado das atividades do Santos', 'Com sintomas desde quinta, Neymar passou por exames e foi afastado das atividades no Santos', 'Abrir mais reações\nO Santos informou neste sábado (7) que Neymar foi diagnosticado com COVID-19.\nDe acordo com o clube, o camisa 10 está afastado das atividades desde a última quinta-feira, quando começou a sentir os primeiros sintomas.\nESPN no Disne... [2184 chars]', 'https://www.espn.com.br/futebol/santos/artigo/_/id/15284328/neymar-e-diagnosticado-covid-19-e-afastado-atividades-santos', 'https://a2.espncdn.com/combiner/i?img=%2Fphoto%2F2025%2F0417%2Fr1479956_1296x729_16%2D9.jpg', '2025-06-07 20:25:00', 'ESPN Brasil', 'https://www.espn.com.br', '2025-06-08 01:04:27', 'pt', 0.0),
(488, '\'para manter relação\' com Tarcísio, dizem aliados', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Bolsonaro está em São Paulo desde ontem para se preparar para o julgamento no STF (Supremo Tribunal Federal) sobre a tentativa de golpe de Estado. Ele terá reuniões com advogados para preparar estratégias de defesa e os pontos que pretende questionar... [1301 chars]', 'https://noticias.uol.com.br/politica/ultimas-noticias/2025/06/07/tarcisio-palacio-bandeirantes-jair-bolsonaro.htm', 'https://conteudo.imguol.com.br/c/noticias/4d/2025/03/12/jair-bolsonaro-e-tarcisio-de-freitas-participam-de-evento-em-sao-paulo-1741800847427_v2_615x300.jpg', '2025-06-08 00:02:03', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:53', 'pt', 0.0),
(489, 'Advogado crítico de Bukele é detido em El Salvador', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Anaya é colunista de veículos de comunicação e participava de programas de TV em que criticava abertamente decisões do governo, em particular a política de segurança, e a reeleição. O presidente salvadorenho acusa seus críticos de ativismo político d... [1293 chars]', 'https://noticias.uol.com.br/ultimas-noticias/afp/2025/06/07/advogado-critico-de-bukele-e-detido-em-el-salvador.htm', 'https://conteudo.imguol.com.br/c/interacao/facebook/share/noticias-min.png', '2025-06-07 23:28:40', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:53', 'pt', 0.0),
(490, 'Vídeo mostra trajeto de drone da Ucrânia em ataque a aviões russos', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Operação foi batizada de Teia de Aranha. O presidente Volodymyr Zelensky declarou que a ação, é a de mais longo alcance já realizada pela Ucrânia e classificou o ataque como \"brilhante\".\nA base de Irkutsk abriga o bombardeiro supersônico Tupolev Tu-2... [1362 chars]', 'https://noticias.uol.com.br/internacional/ultimas-noticias/2025/06/07/video-mostra-trajeto-de-drone-da-ucrania-em-ataque-a-superavioes-russos.htm', 'https://conteudo.imguol.com.br/c/noticias/f2/2025/06/02/1jun2025---captura-de-um-video-divulgado-pelo-servico-secreto-ucraniano-mostra-o-que-eles-dizem-ser-varias-aeronaves-russas-em-chamas-na-base-aerea-de-belaya-no-leste-da-siberia-1748863852525_v2_615x', '2025-06-07 23:23:36', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:53', 'pt', 0.0),
(491, 'Itália deve retribuir diplomacia e devolver Zambelli, diz professor', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'O ministro Alexandre de Moraes, do STF (Supremo Tribunal Federal), pediu para que o Ministério da Justiça formalize o pedido de extradição da deputada licenciada Carla Zambelli. Ele também mandou que o presidente da Câmara, Hugo Motta, seja notificad... [1557 chars]', 'https://noticias.uol.com.br/internacional/ultimas-noticias/2025/06/07/italia-deve-retribuir-diplomacia-e-devolver-zambelli-analisa-professor.htm', 'https://conteudo.imguol.com.br/c/noticias/5d/2024/07/24/deputada-federal-carla-zambelli-pl-sp-1721844480557_v2_615x300.jpg', '2025-06-07 22:12:10', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:53', 'pt', 0.0),
(492, 'Milhares de pessoas pedem em Tel Aviv libertação de reféns em Gaza', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Milhares de pessoas manifestaram-se neste sábado em Tel Aviv para pedir a libertação dos reféns mantidos na Faixa de Gaza e um cessar-fogo no território palestino, após 20 meses de conflito entre Israel e o movimento islamita Hamas.\nA multidão se con... [459 chars]', 'https://noticias.uol.com.br/ultimas-noticias/afp/2025/06/07/milhares-de-pessoas-pedem-em-tel-aviv-libertacao-de-refens-em-gaza.htm', 'https://conteudo.imguol.com.br/c/interacao/facebook/share/noticias-min.png', '2025-06-07 21:10:33', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:54', 'pt', 0.0),
(493, 'Justiça manda prender mulher, troca CPF e Sakamoto é parado pela PM', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'O Tribunal de Justiça do Paraná emitiu um mandado de prisão contra uma mulher, mas usou o CPF de outra pessoa: o jornalista Leonardo Sakamoto, colunista do UOL.\nO mandado, de 3 de junho, foi incluído no banco de dados do CNJ (Conselho Nacional de Jus... [278 chars]', 'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2025/06/07/justica-manda-prender-mulher-troca-cpf-e-sakamoto-e-parado-pela-pm.htm', 'https://conteudo.imguol.com.br/c/noticias/07/2025/06/07/leonardo-sakamoto-na-apresentacao-do-uol-news-em-7-de-junho-no-caminho-para-o-uol-foi-abordado-duas-vezes-pela-pm-1749329097033_v2_615x300.png', '2025-06-07 20:41:50', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:54', 'pt', 0.0),
(494, 'Vance diz que Musk se tornou ?nuclear?, mas espera sua volta à ?turma?', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Vance ressaltou sua \"lealdade\" a Trump e classificou Musk como \"um cara emotivo\" e \"novo na política\". \"Acredito que ele [Musk] olhou para o orçamento [federal], não gostou, (...) e tem o direito de ter uma opinião. Mas acredito que é um grande erro ... [2029 chars]', 'https://noticias.uol.com.br/internacional/ultimas-noticias/2025/06/07/vance-diz-que-musk-se-tornou-nuclear-mas-que-espera-sua-volta-a-turma.htm', 'https://conteudo.imguol.com.br/c/noticias/f1/2025/06/07/donald-trump-com-jd-vance-e-elon-musk-durante-evento-esportivo-no-fim-de-2024-1749327421284_v2_615x300.png', '2025-06-07 20:40:08', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:55', 'pt', 0.0),
(495, 'Alemanha acelera plano para ampliar rede de bunkers sob temor de ataque russo', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Alemanha acelera plano para ampliar rede de bunkers sob temor de ataque russo - País planeja entregar nos próximos meses uma estratégia nacional para proteger população civil em caso de ataque. Expectativa é ampliar capacidade de abrigos de emergênci... [815 chars]', 'https://noticias.uol.com.br/ultimas-noticias/deutschewelle/2025/06/07/alemanha-acelera-plano-para-ampliar-rede-de-bunkers-sob-temor-de-ataque-russo.htm', 'https://conteudo.imguol.com.br/c/interacao/facebook/share/noticias-min.png', '2025-06-07 20:22:00', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:55', 'pt', 0.0),
(496, 'Barroso: \'Constituição brasileira permite que tudo possa chegar à Suprema Corte\'', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'O presidente do Supremo Tribunal Federal (STF), Luís Roberto Barroso, voltou a refutar às afirmações de que a Suprema Corte se mete em tudo que é assunto no País. Durante participação neste sábado, 7, no Fórum Esfera, no Guarujá, Litoral Sul de São P... [716 chars]', 'https://noticias.uol.com.br/ultimas-noticias/agencia-estado/2025/06/07/barroso-constituicao-brasileira-permite-que-tudo-possa-chegar-a-suprema-corte.htm', 'https://conteudo.imguol.com.br/c/interacao/facebook/share/noticias-min.png', '2025-06-07 20:00:00', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:55', 'pt', 0.0),
(497, 'Mulher é resgatada após 22 anos em condição análoga à escravidão em AM', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Uma mulher de 34 anos foi resgatada em Manaus (AM) após passar 22 anos vivendo em condição análoga à escravidão.\nO que aconteceu\nA mulher foi encontrada trabalhando sem remuneração mínima, submetida a jornadas exaustivas e sem condições de viver de f... [576 chars]', 'https://noticias.uol.com.br/cotidiano/ultimas-noticias/2025/06/07/mulher-e-resgatada-apos-22-anos-em-condicao-analoga-a-escravidao-em-am.htm', 'https://conteudo.imguol.com.br/c/noticias/fe/2025/06/07/trabalhadora-domestica-de-34-anos-trabalhava-desde-os-12-anos-para-familia-em-manaus-1749325113035_v2_615x300.jpg', '2025-06-07 19:53:18', 'UOL', 'https://noticias.uol.com.br', '2025-06-08 01:13:55', 'pt', 0.0),
(511, 'Veja os números sorteados no concurso 3412 da Lotofácil, com prêmio de R$ 1,8 milhão', 'A Caixa Econômica Federal sorteia neste sábado (7) o concurso 3412 da Lotofácil. O prêmio para quem acertar as 15 dezenas sorteadas é de R$ 1,8 milhão. O', 'Veja os números sorteados no concurso 3412 da Lotofácil, com prêmio de R$ 1,8 milhão\nSorteio será realizado a partir das 20h deste sábado (7)\nQuem acertar os números premiados leva para casa R$ 1,8 milhão (Foto: Rodrigo de Oliveira, Caixa, Divulgação... [1214 chars]', 'https://www.nsctotal.com.br/noticias/veja-os-numeros-sorteados-no-concurso-3412-da-lotofacil-com-premio-de-r-18-milhao', 'https://img.nsctotal.com.br/wp-content/uploads/2025/05/lotofacil-285.jpg', '2025-06-08 00:32:06', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 01:52:07', 'pt', 0.0),
(512, 'Loterias: Mega-Sena sorteia R$ 51 milhões; confira as dezenas', 'Caixa Econômica Federal também sorteou os números da Lotofácil, Timemania, Quina, Dia de Sorte e +Milionária no Espaço da Sorte', 'A Caixa Econômica Federal sorteou, na noite deste sábado (7/6), os concursos de número 3.412, da Lotofácil; 6.750, da Quina; 2.253, da Timemania; 2.873, da Mega-Sena; 1.074, da Dia de Sorte e 257 da +Milionária.\nOs números foram sorteados às 20h no E... [445 chars]', 'https://www.metropoles.com/brasil/loterias-mega-sena-sorteia-r-51-milhoes-confira-as-dezenas', 'https://uploads.metroimg.com/wp-content/uploads/2024/10/17190412/Imagem-ilustrativa-lote%CC%81rica-Mega-Sena-jogos-sorteio-CAIXA-Metropoles-6-e1730853565841.jpg', '2025-06-07 23:18:00', 'Metrópoles', 'https://www.metropoles.com', '2025-06-08 01:52:07', 'pt', 0.0),
(520, 'Mega-Sena: 3 apostas do DF acertam a quina e faturam R$ 44 mil', 'Os números sorteados neste sábado foram: 04 – 05 – 17 – 27 – 52 – 56', 'O concurso de número 2873 da Mega-Sena, realizado neste sábado (20/5), premiou com R$ 44,3 mil três apostadores do Distrito Federal. Os sortudos acertaram a quina no concurso da Caixa Econômica Federal.\nAs três apostas vencedoras foram feitas de form... [927 chars]', 'https://www.metropoles.com/distrito-federal/mega-sena-3-apostas-do-df-acertam-a-quina-e-faturam-r-44-mil', 'https://uploads.metroimg.com/wp-content/uploads/2024/11/07074640/Mega-sena-12.jpg', '2025-06-08 10:08:00', 'Metrópoles', 'https://www.metropoles.com', '2025-06-08 13:09:31', 'pt', 1.0),
(521, 'Eminem processa Mark Zuckerberg e pede R$ 550 milhões por uso indevido de música', 'Editora responsável pelos direitos autorais do músico entrou com ação judicial contra a Meta Platforms no final de maio por \'exploração comercial\' sem permissão do rapper', 'O rapper Eminem , conhecido tanto por sua proeza no mundo do rap quanto por sua determinação fora dos palcos, está de volta aos holofotes, desta vez por levar sua voz aos tribunais. O artista, que travou inúmeras batalhas ao longo de sua carreira — d... [4146 chars]', 'https://oglobo.globo.com/cultura/noticia/2025/06/08/eminem-processa-mark-zuckerberg-e-pede-r-550-milhoes-por-uso-indevido-de-musica.ghtml', 'https://s2-oglobo.glbimg.com/fFtnDum5hbVGlx-GkphRgNAGoQI=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2025/l/K/CAB0CJTBu5lHO6plW9PA/fotojet-1-.jpg', '2025-06-08 07:00:53', 'O Globo', 'https://oglobo.globo.com', '2025-06-08 12:42:29', 'pt', 0.0),
(522, 'De \'patinho feio\' a novo galã de \'Vale tudo\', Thomás Aquino celebra fase na carreira: \'me explodo de felicidade\'', 'Ator também é protagonista de \'Guerreiros do sol\', nova novela original do Globoplay', 'Se explodindo de felicidade. É como Thomás Aquino descreve o atual momento em sua carreira. Na quarta-feira (11), o ator chega às telinhas do Globoplay como protagonista de “ Guerreiros do sol ”, novela original da plataforma escrita por George Moura... [4979 chars]', 'https://oglobo.globo.com/cultura/noticia/2025/06/08/de-patinho-feio-a-novo-gala-de-vale-tudo-thomas-aquino-celebra-fase-na-carreira-me-explodo-de-felicidade.ghtml', 'https://s2-oglobo.glbimg.com/iDKUYEA3M0Yj_nC5wU-cFwATpoI=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2025/g/R/PF05FkTpWlZfqQmvBC3Q/111295018-sc-exclusivo-rio-de-janeiro-rj-04-06-2025', '2025-06-08 06:30:29', 'O Globo', 'https://oglobo.globo.com', '2025-06-08 12:42:29', 'pt', 0.0);
INSERT INTO `noticias` (`id`, `title`, `description`, `content`, `url`, `image_url`, `published_at`, `source_name`, `source_url`, `fetched_at`, `lang`, `MEDIA_NOTICIA`) VALUES
(533, 'Colômbia: Presidente promete \"caçar\" responsável por balear rival político', 'Adolescente de 15 anos foi preso após ataque a tiros contra senador colombiano Miguel Uribe', 'Presidente da Colômbia, Petro, diz que nenhuma hipótese está descartada em ataque a tiros contra senador\nAdolescente de 15 anos foi preso após ataque a tiros contra senador colombiano Miguel Uribe\nO senador colombiano Miguel Uribe, candidato à Presid... [5680 chars]', 'https://www.cnnbrasil.com.br/internacional/colombia-presidente-promete-cacar-responsavel-por-balear-rival-politico/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/06/2025-06-08T045447Z_1_LOP015208062025RP1_RTRMADP_BASEIMAGE-960X540_0145-COLOMBIA-POLITICS-URIBE-UPDATE.jpg', '2025-06-08 09:30:10', 'CNN Brasil', 'https://www.cnnbrasil.com.br', '2025-06-08 13:09:31', 'pt', 1.0),
(534, 'Haddad encontra líderes para apresentar \'cardápio\' alternativo ao IOF', 'Encontre orientações e notícias sobre economia: investimentos, finanças, negócios, carreira, cotações de Bolsas, moedas, índices econômicos e mais...', 'Detalhes das propostas estão guardados a sete chaves. Haddad passou os últimos dias conversando com Motta e Alcolumbre para alinhar as medidas que serão apresentadas ao Congresso. Eles combinaram que os pormenores do conjunto de ações não seriam divu... [1615 chars]', 'https://economia.uol.com.br/noticias/redacao/2025/06/08/haddad-encontra-lideres-para-apresentar-cardapio-alternativo-ao-iof.htm', 'https://conteudo.imguol.com.br/c/noticias/3f/2024/11/26/ministro-da-fazenda-fernando-haddad-1732627329778_v2_615x300.jpg', '2025-06-08 08:33:26', 'UOL Economia', 'https://economia.uol.com.br', '2025-06-08 13:09:31', 'pt', 0.0),
(600, 'Trump encerra relação com Elon Musk e ameaça fazer retaliação política', 'Ao ser questionado se considerava a relação encerrada, Trump respondeu: “Eu presumiria que sim”', '247 – O presidente dos Estados Unidos, Donald Trump, declarou neste sábado (7) que sua relação com o bilionário Elon Musk chegou ao fim, após uma escalada de ataques públicos entre os dois. A afirmação foi feita em entrevista telefônica concedida à e... [2223 chars]', 'https://www.brasil247.com/mundo/trump-encerra-relacao-com-elon-musk-e-ameaca-retaliacao-politica', 'https://cdn.brasil247.com/pb-b247gcp/swp/jtjeq9/media/20250606140640_8b8b23a5bd867a4f24fbb015eb7063efa953c8e817e2ddaa29eeb7907d673aee.png', '2025-06-08 06:14:57', 'Brasil 247', 'https://www.brasil247.com', '2025-06-08 12:42:29', 'pt', 0.0),
(601, 'Veterano, Cristiano Ronaldo encara o futuro Bola de Ouro na decisão da Nations League', 'Espanha e Portugal fazem clássico ibérico com destaque para um craque longevo e as estrelas da nova geração', 'Veterano, Cristiano Ronaldo encara o futuro Bola de Ouro na decisão da Nations League Espanha e Portugal fazem clássico ibérico com destaque para um craque longevo e as estrelas da nova geração Futebol|Carol Malheiro*, do R7 08/06/2025 - 02h00 (Atual... [3502 chars]', 'https://esportes.r7.com/futebol/veterano-cristiano-ronaldo-encara-o-futuro-bola-de-ouro-na-decisao-da-nations-league-07062025/', 'https://newr7-r7-prod.web.arc-cdn.net/resizer/v2/C6VVGQQNFJGCZGT6JHPAATQKTU.jpg?smart=true&auth=3e4d6628cb1d72971face4b51920630481bca445acdfd2292918e98e4440d4b2&width=1200&height=630', '2025-06-08 05:00:00', 'R7 Esportes', 'https://esportes.r7.com', '2025-06-08 12:42:29', 'pt', 0.0),
(602, '‘Ofensiva assassina’ de Putin atacará a Ucrânia em três frentes para vencer a guerra', 'Padrão russo de ataque indica que a nova investida pode combinar avanços rápidos e pressão contínua', '‘Ofensiva assassina’ de Putin atacará a Ucrânia em três frentes para vencer a guerra Padrão russo de ataque indica que a nova investida pode combinar avanços rápidos e pressão contínua Internacional|Do R7 08/06/2025 - 02h00 (Atualizado em 08/06/2025 ... [4421 chars]', 'https://noticias.r7.com/internacional/ofensiva-assassina-de-putin-atacara-a-ucrania-em-tres-frentes-para-vencer-a-guerra-08062025/', 'https://newr7-r7-prod.web.arc-cdn.net/resizer/v2/ILQEGWNKT5BADEYZGXEA5LGSSE.png?smart=true&auth=4dcced9574ec3e0c240f9598e626897bb94f2ae181e73bead4fe786a632be40a&width=1200&height=630', '2025-06-08 05:00:00', 'R7', 'https://noticias.r7.com', '2025-06-08 12:42:29', 'pt', 0.0),
(603, 'Vídeo mostra momento em que carro explode em posto de combustível e mata idoso no RJ', 'As imagens das câmeras de segurança de um posto de combustível na Lapa, no Centro do Rio de Janeiro, mostram o momento em que uma explosão mata um idoso', 'Vídeo mostra momento em que carro explode em posto de combustível e mata idoso no RJ\nHomem de 64 anos aguardava atrás do veículo quando ocorreu a explosão\nAs imagens das câmeras de segurança de um posto de combustível na Lapa, no Centro do Rio de Jan... [1350 chars]', 'https://www.nsctotal.com.br/noticias/video-mostra-momento-em-que-carro-explode-em-posto-de-combustivel-e-mata-idoso-no-rj', 'https://img.nsctotal.com.br/wp-content/uploads/2025/06/Reproducao-explosao-posto.jpg', '2025-06-08 03:33:04', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 12:42:29', 'pt', 0.0),
(604, 'Neymar testa positivo para Covid-19 e volta a desfalcar o Santos', 'Neymar testa positivo para a Covid-19 e fica afastado dos treinos do Santos em período de incerteza sobre a sua renovação', 'Neymar testa positivo para Covid-19 e volta a desfalcar o Santos\nDiagnóstico do camisa 10 vem em meio ao período de incerteza da sua continuidade no clube, que tem contrato até o fim de junho\nO Santos confirmou na noite deste sábado (7), que Neymar t... [958 chars]', 'https://www.nsctotal.com.br/noticias/neymar-testa-positivo-para-covid-19-e-volta-a-desfalcar-o-santos', 'https://img.nsctotal.com.br/wp-content/uploads/2025/05/MEU-PADRAO-NSC-TOTAL-2025-05-24T225928.192.jpg', '2025-06-08 02:22:45', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 12:42:29', 'pt', 0.0),
(626, 'Onde assistir Brasil x Itália pela Liga das Nações de Vôlei feminino', 'Confira onde assistir ao vivo e com imagens o jogo entre Brasil e Itália pela Liga das Nações de Vôlei na manhã deste domingo', 'Onde assistir ao vivo Brasil x Itália pela Liga das Nações de Vôlei (VNL) feminino 2025\nSeleção Brasileira faz o último confronto desta primeira etapa da Liga das Nações de Vôlei neste domingo\nBrasil faz último jogo desta fase da VNL (Foto: volleybal... [2292 chars]', 'https://www.nsctotal.com.br/noticias/onde-assistir-ao-vivo-brasil-x-italia-pela-liga-das-nacoes-de-volei-vnl-feminino-2025', 'https://img.nsctotal.com.br/wp-content/uploads/2025/06/Brasil-faz-ultimo-jogo-desta-fase-da-VNL.jpg', '2025-06-08 11:53:33', 'NSC Total', 'https://www.nsctotal.com.br', '2025-06-08 13:09:30', 'pt', 3.0),
(627, 'Lula sugere troca de dívida de países por preservação de oceanos', 'Veja as principais notícias e manchetes do dia no Brasil e no Mundo. Leia textos e assista a vídeos de Política, Cotidiano, Crimes e mais.', 'Lula disse que é urgente \"desburocratizar acesso a a fundos climáticos\". O presidente citou ainda metas adotadas pela Organização Marítima Internacional como zerar emissões de carbono na navegação até 2050 e o aumento da demanda por energias renováve... [1646 chars]', 'https://noticias.uol.com.br/politica/ultimas-noticias/2025/06/08/presidente-lula-forum-de-economia-azul-e-financas.htm', 'https://conteudo.imguol.com.br/c/noticias/62/2025/06/08/lula-participa-do-forum-economia-azul-e-financas-na-franca-1749383092292_v2_615x300.png', '2025-06-08 11:49:25', 'UOL Notícias', 'https://noticias.uol.com.br', '2025-06-08 13:09:30', 'pt', 3.0),
(628, 'Vídeo mostra explosão de carro que deixou um morto e um ferido no Rio', 'Com o impacto da explosão, o teto do posto de gasolina ficou destruído; estilhaços atingiram prédios próximos, como o do Instituto Nacional do Câncer (INCA)', 'Câmeras de segurança mostram explosão de carro em posto de combustíveis no centro do Rio\nCom o impacto da explosão, o teto do posto de gasolina ficou destruído; estilhaços atingiram prédios próximos, como o do Instituto Nacional do Câncer (INCA)\nVíde... [1538 chars]', 'https://www.cnnbrasil.com.br/nacional/sudeste/rj/video-mostra-explosao-de-carro-que-deixou-um-morto-e-um-ferido-no-rio/', 'https://admin.cnnbrasil.com.br/wp-content/uploads/sites/12/2025/06/explode-posto.png', '2025-06-08 11:02:29', 'CNN Brasil', 'https://www.cnnbrasil.com.br', '2025-06-08 13:09:31', 'pt', 0.0),
(648, 'Como tratar sinusite e evitar complicações como meningite', 'Médicos afirmam que, em casos raros, condição comum no outono e no inverno pode evoluir para quadro grave', 'São Paulo\nInflamação da mucosa que reveste os seios da face e o nariz, a sinusite é comum no outono e no inverno, épocas em que há maior circulação de vírus respiratórios em geral. Em 98% dos casos, a condição é causada por infecções virais.\nOs sinto... [3460 chars]', 'https://www1.folha.uol.com.br/equilibrioesaude/2025/06/saiba-como-tratar-sinusite-e-evitar-complicacoes-como-meningite.shtml', 'https://f.i.uol.com.br/fotografia/2023/08/23/169281059364e63d617be76_1692810593_3x2_xl.jpg', '2025-06-08 10:00:00', 'Folha de S.Paulo', 'https://www1.folha.uol.com.br', '2025-06-08 13:09:31', 'pt', 0.0),
(650, 'Leão XIV em Pentecostes: invocar o Espírito do amor e da paz para abrir as fronteiras do coração', 'As fronteiras a serem abertas pelo Sopro divino, disse o Pontífice em homilia na Praça São Pedro na Solenidade de Pentecostes, estão \"dentro de nós, ...', 'As fronteiras a serem abertas pelo Sopro divino, disse o Pontífice em homilia na Praça São Pedro na Solenidade de Pentecostes, estão \"dentro de nós, nas nossas relações e entre os povos\". Os milhares de peregrinos do Jubileu dos Movimentos, Associaçõ... [5525 chars]', 'https://www.vaticannews.va/pt/papa/news/2025-06/papa-leao-xiv-solenidade-pentecostes-jubileu-movimentos-junho-25.html', 'https://www.vaticannews.va/content/dam/vaticannews/agenzie/images/srv/2025/06/08/2025-06-08-santa-messa-nella-solennita-di-pentecoste--per-il-giu/1749372437314.JPG/_jcr_content/renditions/cq5dam.thumbnail.cropped.1500.844.jpeg', '2025-06-08 09:13:44', 'Vatican News', 'https://www.vaticannews.va', '2025-06-08 13:09:31', 'pt', 0.0),
(652, 'Portugal x Espanha: horário e onde assistir à final da Liga das Nações', 'Final da Liga das Nações da UEFA acontece neste domingo (8) em Munique. Confira a transmissão ao vivo e saiba em qual canal vai passar', 'Portugal e Espanha entram em campo na tarde de hoje, às 16h (de Brasília), na Allianz Arena, em Munique, pela final da Liga das Nações da Uefa.\nOnde assistir? Sportv (TV por assinatura), ESPN (TV por assinatura) e Disney+ (streaming —de acordo com as... [284 chars]', 'https://www.uol.com.br/esporte/ultimas-noticias/2025/06/08/portugal-x-espanha-onde-assistir-a-final-da-liga-das-nacoes.htm', 'https://conteudo.imguol.com.br/c/esporte/a9/2025/06/05/yamal-comemora-gol-marcado-pela-espanha-contra-a-franca-na-liga-das-nacoes-1749155634976_v2_615x300.jpg', '2025-06-08 08:30:00', 'UOL', 'https://www.uol.com.br', '2025-06-08 13:09:31', 'pt', 0.0),
(653, 'Revolução dos drones: Indústria militar ucraniana se reinventa com a guerra e já põe o futuro na mira', 'Engessamento da indústria local começou a ser desfeito após guerra no leste do país, e urgência existencial de defesa nacional alçou a Ucrânia a \'potência dos drones\'', 'Cerca de duas semanas antes de Vladimir Putin ordenar a maior invasão terrestre em solo europeu desde a Segunda Guerra Mundial, o então chefe do Estado-Maior dos EUA, Mark Milley, afirmou a parlamentares que, caso os russos entrassem na Ucrânia , Kie... [8265 chars]', 'https://oglobo.globo.com/mundo/noticia/2025/06/08/revolucao-dos-drones-industria-militar-ucraniana-se-reinventa-com-a-guerra-e-ja-poe-o-futuro-na-mira.ghtml', 'https://s2-oglobo.glbimg.com/6hWKPxpMwidNApI7f7Fc97vFJCw=/1200x/smart/filters:cover():strip_icc()/i.s3.glbimg.com/v1/AUTH_da025474c0c44edd99332dddb09cabe8/internal_photos/bs/2025/l/O/KdeyfoR3qaAC0xvXoeeQ/111065937-in-this-handout-photograph-taken-on-may-1', '2025-06-08 07:30:22', 'O Globo', 'https://oglobo.globo.com', '2025-06-08 13:09:31', 'pt', 0.0);

--
-- Índices para tabelas despejadas
--

--
-- Índices de tabela `feedbacks`
--
ALTER TABLE `feedbacks`
  ADD PRIMARY KEY (`FEEDBACKS_ID`),
  ADD KEY `NOTICIAS_ID` (`NOTICIAS_ID`);

--
-- Índices de tabela `noticias`
--
ALTER TABLE `noticias`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `url` (`url`);

--
-- AUTO_INCREMENT para tabelas despejadas
--

--
-- AUTO_INCREMENT de tabela `feedbacks`
--
ALTER TABLE `feedbacks`
  MODIFY `FEEDBACKS_ID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=23;

--
-- AUTO_INCREMENT de tabela `noticias`
--
ALTER TABLE `noticias`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=683;

--
-- Restrições para tabelas despejadas
--

--
-- Restrições para tabelas `feedbacks`
--
ALTER TABLE `feedbacks`
  ADD CONSTRAINT `feedbacks_ibfk_1` FOREIGN KEY (`NOTICIAS_ID`) REFERENCES `noticias` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
